export const books = [
  { id: 1, title: 'Introduction to Natural Language Processing', author: 'Jacob Eisenstein', description: 'A comprehensive guide to natural language processing, covering machine learning algorithms, deep learning, and linguistic structures. Essential for AI research.', category: 'Computer Science', coverColor: 'linear-gradient(135deg, #FF6B6B, #556270)' },
  { id: 2, title: 'Deep Learning', author: 'Ian Goodfellow', description: 'The definitive textbook on deep learning, covering mathematical and conceptual background, and core techniques in artificial neural networks.', category: 'Computer Science', coverColor: 'linear-gradient(135deg, #4facfe, #00f2fe)' },
  { id: 3, title: 'The Design of Everyday Things', author: 'Don Norman', description: 'Shows how cognitive psychology applies to the design of everyday products and user interfaces. A must-read for UX designers.', category: 'Design', coverColor: 'linear-gradient(135deg, #f093fb, #f5576c)' },
  { id: 4, title: 'Sapiens: A Brief History of Humankind', author: 'Yuval Noah Harari', description: 'Explores the history of the human species, from the Stone Age up to the twenty-first century. A deep dive into anthropology and sociology.', category: 'History', coverColor: 'linear-gradient(135deg, #84fab0, #8fd3f4)' },
  { id: 5, title: 'Atomic Habits', author: 'James Clear', description: 'Practical strategies for forming good habits, breaking bad ones, and mastering the tiny behaviors that lead to remarkable results. Great for self improvement.', category: 'Self-Help', coverColor: 'linear-gradient(135deg, #a18cd1, #fbc2eb)' },
  { id: 6, title: 'Clean Code', author: 'Robert C. Martin', description: 'A handbook of agile software craftsmanship, focusing on writing readable, maintainable code. Perfect for software engineers.', category: 'Computer Science', coverColor: 'linear-gradient(135deg, #f6d365, #fda085)' },
  { id: 7, title: 'The Lean Startup', author: 'Eric Ries', description: 'How today\'s entrepreneurs use continuous innovation to create radically successful businesses. Focuses on product validation.', category: 'Business', coverColor: 'linear-gradient(135deg, #ff0844, #ffb199)' },
  { id: 8, title: 'A Brief History of Time', author: 'Stephen Hawking', description: 'An exploration of cosmology, black holes, and the nature of time and the universe. Physics for everyone.', category: 'Science', coverColor: 'linear-gradient(135deg, #13547a, #80d0c7)' },
  { id: 9, title: 'Thinking, Fast and Slow', author: 'Daniel Kahneman', description: 'A deep dive into the two systems that drive the way we think: System 1 (fast, intuitive) and System 2 (slow, analytical). Explores behavioral economics.', category: 'Psychology', coverColor: 'linear-gradient(135deg, #ff9a9e, #fecfef)' },
  { id: 10, title: 'Guns, Germs, and Steel', author: 'Jared Diamond', description: 'A short history of everybody for the last 13,000 years, exploring the fates of human societies through geography and environment.', category: 'History', coverColor: 'linear-gradient(135deg, #00c6fb, #005bea)' },
  { id: 11, title: 'Design Patterns', author: 'Erich Gamma et al.', description: 'Elements of Reusable Object-Oriented Software. The foundational book for software architecture patterns.', category: 'Computer Science', coverColor: 'linear-gradient(135deg, #e0c3fc, #8ec5fc)' },
  { id: 12, title: 'The Selfish Gene', author: 'Richard Dawkins', description: 'An introduction to the theory of evolution, looking at biology and genetics from the perspective of the gene.', category: 'Science', coverColor: 'linear-gradient(135deg, #43e97b, #38f9d7)' },
  { id: 13, title: 'Artificial Intelligence: A Modern Approach', author: 'Stuart Russell', description: 'The leading textbook in Artificial Intelligence. Covers knowledge representation, reasoning, planning, and machine learning.', category: 'Computer Science', coverColor: 'linear-gradient(135deg, #fa709a, #fee140)' },
  { id: 14, title: 'Steve Jobs', author: 'Walter Isaacson', description: 'The exclusive biography of the visionary Apple founder, detailing his life, personality, and approach to product design.', category: 'Biography', coverColor: 'linear-gradient(135deg, #667eea, #764ba2)' }
];
